### ISSUE TITLE
Optional usability improvements

### ISSUE THREAD

**Issue by cdstanford** [DavisPL/cargo-sherlock#3]
Things that would be nice to have (later):

- [x] make the version argument optional (run most recent by default)

- [x] make the `token.txt` optional (and modify the error message to say that it is optional)

- [x] prompt the user to add the GitHub access token `token.txt` when running `make`.

- [x] can we display the assumptions in English / slightly more helpful way? instead of `a1_syn-2.0.77`

- [x] save the audit trust report to a file (on `-a`)

- [x] optionally add a flag to specify the output file (for either logging or `-a` or both)

- [x] rename `detective.py` to `sherlock.py`?

- [x] log and `-a` could be separate subcommands instead of `-a` being a flag

- [x] consider adding a flag to hide Z3 logging information
```
==================================
Solving for minimum weight of assumptions for tokio-1.40.0...
Number of Z3 Variables: 8
Formula Construction Time: 0.023 sec
Minimum weight of assumptions for tokio-1.40.0: 60
Z3 Solving Time: 0.004 sec
Z3 Num Conflicts: 5
```

**Comment by abasu2** [comment]
> consider adding a flag to hide Z3 logging information

Z3 logging information is now stored in logs/solver!

**Comment by muhammad-hassnain** [comment]
separate sub commands added.
